"""corrected typo

Revision ID: 16068c9ad83a
Revises: 9876aac2ce99
Create Date: 2024-01-29 17:40:14.148923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16068c9ad83a'
down_revision = '9876aac2ce99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('ix_User_username')

    op.drop_table('User')
    op.drop_table('Message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.INTEGER(), nullable=True),
    sa.Column('recipient', sa.INTEGER(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['recipient'], ['User.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('passord_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index('ix_User_username', ['username'], unique=1)

    # ### end Alembic commands ###
