"""added created to Message

Revision ID: 336b80b64f59
Revises: a9ec13eef493
Create Date: 2024-01-30 21:03:11.012969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336b80b64f59'
down_revision = 'a9ec13eef493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Message', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
